[www]

pm = dynamic
pm.max_children = 26
pm.start_servers = 6
pm.min_spare_servers = 4
pm.max_spare_servers = 10

pm.max_requests = 500

pm.status_path = /fpm-status
ping.path = /fpm-ping
ping.response = pong
