date.timezone = UTC
memory_limit = 512M
max_execution_time = 300
max_input_time = 240
max_input_vars = 5000

; ====== Uploads ======
file_uploads = On
upload_max_filesize = 256M
post_max_size = 256M
max_file_uploads = 20

; ====== Errors & Logging ======
display_errors = Off
log_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

; ====== Security-ish toggles ======
allow_url_fopen = On
expose_php = Off
short_open_tag = Off

; ====== Sessions ======
session.cookie_lifetime = 0
session.gc_maxlifetime = 1440
; path session ke larapel
session.save_path = "/var/www/html/storage/framework/sessions"

; session.cookie_secure = On
; session.cookie_httponly = On
; session.cookie_samesite = Lax

; ====== Output ======
zlib.output_compression = Off

; ====== OPCache ======
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 16229
opcache.max_file_size = 262144
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2
